// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyIXrVxi6puID1wcyZVLfYc4OzEQIXtbs',
    appId: '1:885688384894:web:ed796a036fa9f5c9db072f',
    messagingSenderId: '885688384894',
    projectId: 'sparklink-alu',
    authDomain: 'sparklink-alu.firebaseapp.com',
    storageBucket: 'sparklink-alu.firebasestorage.app',
    measurementId: 'G-MTN8L44NRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTfbjDrOi5W3-xJNk35yhDardVqcWcZGg',
    appId: '1:885688384894:android:9991e624561c8845db072f',
    messagingSenderId: '885688384894',
    projectId: 'sparklink-alu',
    storageBucket: 'sparklink-alu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nNFlfqx0ek-ArPUv488sDFyqOryIDNk',
    appId: '1:885688384894:ios:f1677b19aff108bddb072f',
    messagingSenderId: '885688384894',
    projectId: 'sparklink-alu',
    storageBucket: 'sparklink-alu.firebasestorage.app',
    iosBundleId: 'com.example.sparklink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4nNFlfqx0ek-ArPUv488sDFyqOryIDNk',
    appId: '1:885688384894:ios:f1677b19aff108bddb072f',
    messagingSenderId: '885688384894',
    projectId: 'sparklink-alu',
    storageBucket: 'sparklink-alu.firebasestorage.app',
    iosBundleId: 'com.example.sparklink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyIXrVxi6puID1wcyZVLfYc4OzEQIXtbs',
    appId: '1:885688384894:web:37ac76f28d8ac3f1db072f',
    messagingSenderId: '885688384894',
    projectId: 'sparklink-alu',
    authDomain: 'sparklink-alu.firebaseapp.com',
    storageBucket: 'sparklink-alu.firebasestorage.app',
    measurementId: 'G-TZ1T6WXB4S',
  );
}
